"""new m

Revision ID: 457fd445083e
Revises: 77782c604964
Create Date: 2023-11-20 13:15:49.974334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457fd445083e'
down_revision = '77782c604964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_updated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_code', schema=None) as batch_op:
        batch_op.drop_column('is_updated')

    # ### end Alembic commands ###
