"""empty message

Revision ID: 77782c604964
Revises: 
Create Date: 2023-11-18 15:23:50.263453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77782c604964'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_ad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_fk', sa.Integer(), nullable=True),
    sa.Column('ad_index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_ad')
    # ### end Alembic commands ###
